language: node_js
node_js:
  - "lts/*"
script:
  - npx lerna bootstrap
  - npm run lint
  - npm test -- --watchAll=false
  - npm run build
notifications:
  email:
    on_success: change
    on_failure: change
